@startuml
' Диаграмма классов для ИТЗ
skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor LightBlue
    BorderColor Black
    ArrowColor Black
}

usecase "UC1: Регистрация" as UC1
usecase "UC2: Проснуться в лесу" as UC2
usecase "UC3: Сорвать танго" as UC3
usecase "UC4: Предложение торговца" as UC4
usecase "UC5: Кража монеты" as UC5
usecase "UC6: Ранение" as UC6
usecase "UC7: Выбор нового  предмета" as UC7
usecase "UC8: Force Staff" as UC8
usecase "UC9: Linken's Sphere" as UC9
usecase "UC10: Ghost Scepter" as UC10
usecase "UC11: Встреча с пуджом" as UC11
usecase "UC12: Встреча с клоком" as UC12
usecase "UC13: Встреча с фантомкой" as UC13
usecase "UC14: Концовка" as UC14


' Отношения
UC1 --> UC2
UC2 --> UC3
UC3 --> UC4
UC4 --> UC5
UC4 --> UC6
UC5 --> UC7
UC6 --> UC7
UC7 --> UC8
UC7 --> UC9
UC7 --> UC10
UC8 --> UC12
UC9 --> UC11
UC10 --> UC13
UC11 --> UC14
UC12 --> UC14
UC13 --> UC14
@enduml