@startuml
skinparam database {
    BackgroundColor LightPink
    BorderColor Black
    ArrowColor Black
}

class Items {
- name
- emoji
- type
}

class Player {
- player_name
}

class Inventory {
      - add_item
      - show_inventory
      - delete_item
      - use_item
      }

class Targets {
- purpose
}


Player -->  Items
Player -->  Inventory
Player -->  Targets
@enduml